version: '3.7'

services:
  webapp:
    build: .
    image: django_app
    container_name: django_webapp
    restart: always
    environment:
      TZ: Asia/Tokyo
      ALLOWED_HOSTS: 'localhost, 127.0.0.1'
      DB_ENGINE: postgresql
      DB_HOST: django_postgres
      DB_NAME: django
      DB_USER: django
      DB_PASS: django
      EMAIL_BACKEND: smtp
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'true'
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_LOCALTIME: 'false'
      DEFAULT_FROM_EMAIL: ''
      STATIC_ROOT: '/static'
    volumes:
      - django_statics:/static:rw
    depends_on:
      - postgres

  batch:
    image: django_app
    container_name: django_batch
    restart: always
    command: batch
    environment:
      TZ: Asia/Tokyo
      DB_ENGINE: postgresql
      DB_HOST: django_postgres
      DB_NAME: django
      DB_USER: django
      DB_PASS: django
      EMAIL_BACKEND: smtp
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'true'
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_LOCALTIME: 'false'
      DEFAULT_FROM_EMAIL: ''
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1-alpine
    container_name: django_postgres
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      TZ: Asia/Tokyo
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: steveltn/https-portal:1
    container_name: django_nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: 'localhost'
      # STAGE: 'production'
      TZ: Asia/Tokyo
    volumes:
      - django_statics:/var/www/vhosts/localhost/static:ro
      - ./nginx_uwsgi.ssl.conf.erb:/var/lib/nginx-conf/localhost.ssl.conf.erb:ro
      - ssl_certs:/var/lib/https-portal
    depends_on:
      - django_webapp

volumes:
  pgdata:
    driver: local
  django_statics:
    driver: local
  ssl_certs:
    driver: local
