version: '3'

services:
  django-docker:
    container_name: django-docker-compose
    build: .
    working_dir: /code
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    command: >
      sh -c "apk update &&
             apk add bash &&
             apk add git &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
